GET http://localhost:8000/api/users/

###

GET http://localhost:8000/api/users/5ea6f0c234a1762a54186904

###

POST http://localhost:8000/api/users/
content-type: application/json

{
  "id": "0abb4a76-a6c1-4724-a38e-c898c97c7916"
}

###